// PEPMASTERS — Traduções centralizadas
// Idiomas: en (default), pt, es, de, fr

window.PEPMASTERS_I18N = {

  // ── GERAL ──────────────────────────────────────
  'nav.home':          { en:'Home',        pt:'Início',      es:'Inicio',     de:'Start',       fr:'Accueil' },
  'nav.products':      { en:'Products',    pt:'Produtos',    es:'Productos',  de:'Produkte',    fr:'Produits' },
  'nav.about':         { en:'About Us',    pt:'Quem Somos',  es:'Nosotros',   de:'Über uns',    fr:'À propos' },
  'nav.faq':           { en:'FAQ',         pt:'Dúvidas',     es:'Preguntas',  de:'FAQ',         fr:'FAQ' },
  'nav.track':         { en:'Track Order', pt:'Rastrear',    es:'Rastrear',   de:'Verfolgen',   fr:'Suivre' },
  'nav.cart':          { en:'Cart',        pt:'Carrinho',    es:'Carrito',    de:'Warenkorb',   fr:'Panier' },
  'nav.login':         { en:'Login',       pt:'Entrar',      es:'Ingresar',   de:'Anmelden',    fr:'Connexion' },
  'nav.register':      { en:'Register',    pt:'Cadastrar',   es:'Registrarse',de:'Registrieren',fr:'S\'inscrire' },
  'nav.orders':        { en:'Orders',      pt:'Pedidos',     es:'Pedidos',    de:'Bestellungen',fr:'Commandes' },
  'nav.logout':        { en:'Logout',      pt:'Sair',        es:'Salir',      de:'Abmelden',    fr:'Déconnexion' },
  'nav.hello':         { en:'Hi',          pt:'Olá',         es:'Hola',       de:'Hallo',       fr:'Salut' },

  // ── HERO ──────────────────────────────────────
  'hero.eyebrow':      { en:'High performance peptides',  pt:'Peptídeos de alta performance', es:'Péptidos de alto rendimiento', de:'Hochleistungs-Peptide',    fr:'Peptides haute performance' },
  'hero.title1':       { en:'Elevate your',               pt:'Eleve seu',                     es:'Eleva tu',                     de:'Steigere dein',            fr:'Élevez votre' },
  'hero.title2':       { en:'potential',                  pt:'potencial',                     es:'potencial',                    de:'Potenzial',                fr:'potentiel' },
  'hero.title3':       { en:'to the max',                 pt:'ao máximo',                     es:'al máximo',                    de:'auf das Maximum',          fr:'au maximum' },
  'hero.subtitle':     { en:'Bioactive peptides for recovery, body composition and performance. Quality you can trust.', pt:'Peptídeos bioativos para recuperação, composição corporal e performance. Qualidade que você pode confiar.', es:'Péptidos bioactivos para recuperación, composición corporal y rendimiento. Calidad en la que puedes confiar.', de:'Bioaktive Peptide für Erholung, Körperzusammensetzung und Leistung. Qualität, der Sie vertrauen können.', fr:'Peptides bioactifs pour la récupération, la composition corporelle et la performance. Une qualité en laquelle vous pouvez avoir confiance.' },
  'hero.cta':          { en:'View Products',  pt:'Ver Produtos',  es:'Ver Productos',  de:'Produkte ansehen', fr:'Voir les produits' },

  // ── BANNER ──────────────────────────────────────
  'banner.shipping':   { en:'Worldwide Shipping',   pt:'Entrega para todo o Brasil', es:'Envío mundial',          de:'Weltweiter Versand',      fr:'Livraison mondiale' },
  'banner.payment':    { en:'Secure Payment',        pt:'Pagamento Seguro',           es:'Pago Seguro',            de:'Sichere Zahlung',         fr:'Paiement sécurisé' },
  'banner.quality':    { en:'Guaranteed Quality',    pt:'Qualidade Garantida',        es:'Calidad Garantizada',    de:'Garantierte Qualität',    fr:'Qualité garantie' },

  // ── PRODUTOS ──────────────────────────────────────
  'products.title':    { en:'Our Products',      pt:'Nossos Produtos',  es:'Nuestros Productos', de:'Unsere Produkte',   fr:'Nos Produits' },
  'products.search':   { en:'Search peptide...', pt:'Buscar peptídeo...', es:'Buscar péptido...', de:'Peptid suchen...', fr:'Rechercher peptide...' },
  'products.all':      { en:'All',               pt:'Todos',            es:'Todos',              de:'Alle',             fr:'Tous' },
  'products.empty':    { en:'No products found', pt:'Nenhum produto encontrado', es:'No se encontraron productos', de:'Keine Produkte gefunden', fr:'Aucun produit trouvé' },
  'products.empty.sub':{ en:'Try another filter or search', pt:'Tente outro filtro ou busca', es:'Prueba otro filtro', de:'Anderen Filter versuchen', fr:'Essayez un autre filtre' },
  'btn.add':           { en:'Add to Cart',        pt:'Adicionar ao Carrinho', es:'Agregar al Carrito', de:'In den Warenkorb', fr:'Ajouter au panier' },
  'btn.added':         { en:'Added',              pt:'Adicionado',        es:'Agregado',           de:'Hinzugefügt',      fr:'Ajouté' },
  'btn.soldout':       { en:'Sold Out',           pt:'Esgotado',          es:'Agotado',            de:'Ausverkauft',      fr:'Épuisé' },
  'btn.lastunits':     { en:'Last units',         pt:'Últimas unidades',  es:'Últimas unidades',   de:'Letzte Einheiten', fr:'Dernières unités' },
  'btn.confirm':       { en:'Add to Cart',        pt:'Adicionar ao Carrinho', es:'Agregar',         de:'Hinzufügen',       fr:'Ajouter' },
  'btn.cancel':        { en:'Cancel',             pt:'Cancelar',          es:'Cancelar',           de:'Abbrechen',        fr:'Annuler' },

  // ── CATEGORIAS ──────────────────────────────────────
  'cat.recuperacao':   { en:'Recovery',           pt:'Recuperação',       es:'Recuperación',       de:'Erholung',         fr:'Récupération' },
  'cat.gordura':       { en:'Fat Loss',            pt:'Queima de Gordura', es:'Quema de Grasa',     de:'Fettverbrennung',  fr:'Perte de graisse' },
  'cat.gh':            { en:'GH & Mass',           pt:'GH & Massa',        es:'GH & Masa',          de:'GH & Masse',       fr:'GH & Masse' },
  'cat.cognitivo':     { en:'Cognitive',           pt:'Cognitivo',         es:'Cognitivo',          de:'Kognitiv',         fr:'Cognitif' },
  'cat.hormonal':      { en:'Hormonal',            pt:'Hormonal',          es:'Hormonal',           de:'Hormonal',         fr:'Hormonal' },
  'cat.antioxidante':  { en:'Antioxidant',         pt:'Antioxidante',      es:'Antioxidante',       de:'Antioxidativ',     fr:'Antioxydant' },
  'cat.estetico':      { en:'Aesthetic',           pt:'Estético',          es:'Estético',           de:'Ästhetisch',       fr:'Esthétique' },
  'cat.antiinfla':     { en:'Anti-inflammatory',   pt:'Anti-inflamatório', es:'Antiinflamatorio',   de:'Entzündungshemmend',fr:'Anti-inflammatoire' },

  // ── CARRINHO ──────────────────────────────────────
  'cart.title':        { en:'Cart',           pt:'Carrinho',        es:'Carrito',       de:'Warenkorb',      fr:'Panier' },
  'cart.empty':        { en:'Your cart is empty.\nAdd peptides to get started!', pt:'Seu carrinho está vazio.\nAdicione peptídeos para começar!', es:'Tu carrito está vacío.\n¡Agrega péptidos para comenzar!', de:'Ihr Warenkorb ist leer.\nFügen Sie Peptide hinzu, um zu beginnen!', fr:'Votre panier est vide.\nAjoutez des peptides pour commencer!' },
  'cart.subtotal':     { en:'Subtotal',       pt:'Subtotal',        es:'Subtotal',      de:'Zwischensumme',  fr:'Sous-total' },
  'cart.total':        { en:'Total',          pt:'Total',           es:'Total',         de:'Gesamt',         fr:'Total' },
  'cart.checkout':     { en:'Checkout',       pt:'Finalizar Pedido',es:'Finalizar',     de:'Zur Kasse',      fr:'Commander' },
  'cart.clear':        { en:'Clear cart',     pt:'Limpar carrinho', es:'Vaciar carrito',de:'Warenkorb leeren',fr:'Vider le panier' },

  // ── WAITLIST MODAL ──────────────────────────────────────
  'waitlist.title':    { en:'Notify me when available', pt:'Avise-me quando voltar', es:'Avísame cuando esté disponible', de:'Benachrichtige mich', fr:'Me prévenir' },
  'waitlist.subtitle': { en:'Leave your email and we\'ll notify you when the product is back.', pt:'Deixe seu email e te avisamos quando o produto estiver disponível.', es:'Deja tu email y te avisamos cuando el producto esté disponible.', de:'Hinterlassen Sie Ihre E-Mail und wir benachrichtigen Sie.', fr:'Laissez votre email et nous vous préviendrons.' },
  'waitlist.name':     { en:'Your name',      pt:'Seu nome',        es:'Tu nombre',     de:'Ihr Name',       fr:'Votre nom' },
  'waitlist.email':    { en:'Your email',     pt:'Seu email',       es:'Tu email',      de:'Ihre E-Mail',    fr:'Votre email' },
  'waitlist.btn':      { en:'Notify me',      pt:'Quero ser avisado', es:'Quiero ser avisado', de:'Benachrichtigen', fr:'Me notifier' },

  // ── FOOTER ──────────────────────────────────────
  'footer.desc':       { en:'Performance through science. Bioactive peptides with quality and safety for athletes and enthusiasts.', pt:'Performance através da ciência. Peptídeos bioativos com qualidade e segurança para atletas e entusiastas.', es:'Rendimiento a través de la ciencia. Péptidos bioactivos con calidad y seguridad.', de:'Leistung durch Wissenschaft. Bioaktive Peptide mit Qualität und Sicherheit.', fr:'Performance par la science. Peptides bioactifs de qualité et sécurité.' },
  'footer.institutional': { en:'Institutional', pt:'Institucional', es:'Institucional', de:'Institutionell', fr:'Institutionnel' },
  'footer.support':    { en:'Support',        pt:'Suporte',         es:'Soporte',       de:'Support',        fr:'Support' },
  'footer.account':    { en:'My Account',     pt:'Minha Conta',     es:'Mi Cuenta',     de:'Mein Konto',     fr:'Mon Compte' },
  'footer.about':      { en:'About Us',       pt:'Quem Somos',      es:'Sobre Nosotros',de:'Über uns',       fr:'À propos' },
  'footer.terms':      { en:'Terms of Use',   pt:'Termos de Uso',   es:'Términos de Uso',de:'Nutzungsbedingungen',fr:'Conditions d\'utilisation' },
  'footer.privacy':    { en:'Privacy Policy', pt:'Política de Privacidade', es:'Política de Privacidad', de:'Datenschutz', fr:'Politique de confidentialité' },
  'footer.faq':        { en:'FAQ',            pt:'Dúvidas Frequentes', es:'Preguntas Frecuentes', de:'Häufige Fragen', fr:'Questions fréquentes' },
  'footer.shipping':   { en:'Shipping & Deadlines', pt:'Envio e Prazos', es:'Envíos y Plazos', de:'Versand & Fristen', fr:'Expédition et délais' },
  'footer.returns':    { en:'Returns & Exchanges', pt:'Trocas e Devoluções', es:'Cambios y Devoluciones', de:'Rückgaben', fr:'Retours et échanges' },
  'footer.myorders':   { en:'My Orders',      pt:'Meus Pedidos',    es:'Mis Pedidos',   de:'Meine Bestellungen', fr:'Mes commandes' },
  'footer.profile':    { en:'My Profile',     pt:'Meu Perfil',      es:'Mi Perfil',     de:'Mein Profil',    fr:'Mon profil' },
  'footer.trackorder': { en:'Track Order',    pt:'Rastrear Pedido', es:'Rastrear Pedido',de:'Bestellung verfolgen',fr:'Suivre commande' },
  'footer.rights':     { en:'All rights reserved.', pt:'Todos os direitos reservados.', es:'Todos los derechos reservados.', de:'Alle Rechte vorbehalten.', fr:'Tous droits réservés.' },
  'footer.admin':      { en:'Admin Area',     pt:'Área do Administrador', es:'Área de Administrador', de:'Adminbereich', fr:'Zone admin' },

  // ── LOGIN ──────────────────────────────────────
  'login.title':       { en:'Login',          pt:'Entrar',          es:'Ingresar',      de:'Anmelden',       fr:'Connexion' },
  'login.subtitle':    { en:'Access your account to track your orders', pt:'Acesse sua conta para ver seus pedidos', es:'Accede a tu cuenta para ver tus pedidos', de:'Greifen Sie auf Ihr Konto zu', fr:'Accédez à votre compte' },
  'login.email':       { en:'Email',          pt:'Email',           es:'Email',         de:'E-Mail',         fr:'Email' },
  'login.password':    { en:'Password',       pt:'Senha',           es:'Contraseña',    de:'Passwort',       fr:'Mot de passe' },
  'login.forgot':      { en:'Forgot my password', pt:'Esqueci minha senha', es:'Olvidé mi contraseña', de:'Passwort vergessen', fr:'Mot de passe oublié' },
  'login.btn':         { en:'Login',          pt:'Entrar',          es:'Ingresar',      de:'Anmelden',       fr:'Se connecter' },
  'login.register':    { en:'Don\'t have an account? ',pt:'Não tem conta? ', es:'¿No tienes cuenta? ',de:'Kein Konto? ',fr:'Pas de compte? ' },
  'login.register.link':{ en:'Register',      pt:'Cadastre-se',     es:'Regístrate',    de:'Registrieren',   fr:'S\'inscrire' },
  'login.error':       { en:'Email or password incorrect.', pt:'Email ou senha incorretos.', es:'Email o contraseña incorrectos.', de:'E-Mail oder Passwort falsch.', fr:'Email ou mot de passe incorrect.' },

  // ── CADASTRO ──────────────────────────────────────
  'register.title':    { en:'Create Account', pt:'Criar Conta',     es:'Crear Cuenta',  de:'Konto erstellen',fr:'Créer un compte' },
  'register.subtitle': { en:'Register to track your orders', pt:'Cadastre-se para acompanhar seus pedidos', es:'Regístrate para seguir tus pedidos', de:'Registrieren Sie sich', fr:'Inscrivez-vous pour suivre vos commandes' },
  'register.name':     { en:'First name',     pt:'Nome',            es:'Nombre',        de:'Vorname',        fr:'Prénom' },
  'register.lastname': { en:'Last name',      pt:'Sobrenome',       es:'Apellido',       de:'Nachname',       fr:'Nom' },
  'register.cpf':      { en:'CPF / Tax ID',   pt:'CPF',             es:'Documento',     de:'Steuer-ID',      fr:'ID fiscal' },
  'register.phone':    { en:'Phone',          pt:'Telefone',        es:'Teléfono',      de:'Telefon',        fr:'Téléphone' },
  'register.password': { en:'Password',       pt:'Senha',           es:'Contraseña',    de:'Passwort',       fr:'Mot de passe' },
  'register.confirm':  { en:'Confirm',        pt:'Confirmar',       es:'Confirmar',     de:'Bestätigen',     fr:'Confirmer' },
  'register.btn':      { en:'Create account', pt:'Criar conta',     es:'Crear cuenta',  de:'Konto erstellen',fr:'Créer le compte' },
  'register.login':    { en:'Already have an account? ', pt:'Já tem conta? ', es:'¿Ya tienes cuenta? ', de:'Bereits Konto? ', fr:'Déjà un compte? ' },

  // ── CHECKOUT ──────────────────────────────────────
  'checkout.title':    { en:'Checkout',       pt:'Finalizar Pedido',es:'Finalizar Pedido',de:'Kasse',        fr:'Commander' },
  'checkout.data':     { en:'Your Details',   pt:'Seus Dados',      es:'Tus Datos',     de:'Ihre Daten',     fr:'Vos données' },
  'checkout.fullname': { en:'Full name',      pt:'Nome completo',   es:'Nombre completo',de:'Vollständiger Name',fr:'Nom complet' },
  'checkout.delivery': { en:'Delivery Address',pt:'Endereço de Entrega',es:'Dirección de Entrega',de:'Lieferadresse',fr:'Adresse de livraison' },
  'checkout.zip':      { en:'ZIP Code',       pt:'CEP',             es:'Código Postal',  de:'PLZ',           fr:'Code postal' },
  'checkout.number':   { en:'Number',         pt:'Número',          es:'Número',         de:'Nummer',        fr:'Numéro' },
  'checkout.street':   { en:'Street',         pt:'Rua',             es:'Calle',          de:'Straße',        fr:'Rue' },
  'checkout.district': { en:'District',       pt:'Bairro',          es:'Barrio',         de:'Stadtteil',     fr:'Quartier' },
  'checkout.city':     { en:'City / State',   pt:'Cidade / UF',     es:'Ciudad / Estado',de:'Stadt / Land',  fr:'Ville / Pays' },
  'checkout.complement':{ en:'Complement',    pt:'Complemento',     es:'Complemento',    de:'Zusatz',        fr:'Complément' },
  'checkout.payment':  { en:'Payment',        pt:'Pagamento',       es:'Pago',           de:'Zahlung',       fr:'Paiement' },
  'checkout.summary':  { en:'Order Summary',  pt:'Resumo do Pedido',es:'Resumen del Pedido',de:'Bestellübersicht',fr:'Récapitulatif' },
  'checkout.subtotal': { en:'Subtotal',       pt:'Subtotal',        es:'Subtotal',       de:'Zwischensumme', fr:'Sous-total' },
  'checkout.discount': { en:'Discount',       pt:'Desconto',        es:'Descuento',      de:'Rabatt',        fr:'Remise' },
  'checkout.shipping': { en:'Shipping',       pt:'Frete',           es:'Envío',          de:'Versand',       fr:'Livraison' },
  'checkout.tocalc':   { en:'To calculate',   pt:'A calcular',      es:'A calcular',     de:'Zu berechnen',  fr:'À calculer' },
  'checkout.total':    { en:'Total',          pt:'Total',           es:'Total',          de:'Gesamt',        fr:'Total' },
  'checkout.coupon':   { en:'Discount coupon',pt:'Cupom de desconto',es:'Cupón de descuento',de:'Rabattcode',fr:'Code promo' },
  'checkout.apply':    { en:'Apply',          pt:'Aplicar',         es:'Aplicar',        de:'Anwenden',      fr:'Appliquer' },
  'checkout.finalize': { en:'Place Order',    pt:'Finalizar Pedido',es:'Realizar Pedido',de:'Bestellen',     fr:'Passer la commande' },
  'checkout.secure':   { en:'100% secure payment', pt:'Pagamento 100% seguro', es:'Pago 100% seguro', de:'100% sichere Zahlung', fr:'Paiement 100% sécurisé' },
  'checkout.pix.hint': { en:'Click "Place Order" to generate the PIX QR Code. Automatic confirmation.', pt:'Clique em "Finalizar" para gerar o QR Code PIX. Confirmação automática.', es:'Haz clic en "Realizar" para generar el QR PIX.', de:'Klicken Sie auf "Bestellen", um den PIX-QR-Code zu generieren.', fr:'Cliquez sur "Commander" pour générer le QR Code PIX.' },
  'checkout.empty':    { en:'Your cart is empty', pt:'Seu carrinho está vazio', es:'Tu carrito está vacío', de:'Ihr Warenkorb ist leer', fr:'Votre panier est vide' },
  'checkout.back':     { en:'Continue shopping', pt:'Continuar comprando', es:'Seguir comprando', de:'Weiter einkaufen', fr:'Continuer les achats' },

  // ── MEUS PEDIDOS ──────────────────────────────────────
  'orders.title':      { en:'My Orders',      pt:'Meus Pedidos',    es:'Mis Pedidos',   de:'Meine Bestellungen',fr:'Mes commandes' },
  'orders.empty':      { en:'No orders found', pt:'Nenhum pedido encontrado', es:'No se encontraron pedidos', de:'Keine Bestellungen gefunden', fr:'Aucune commande trouvée' },
  'orders.track':      { en:'Track',          pt:'Rastrear',        es:'Rastrear',      de:'Verfolgen',      fr:'Suivre' },
  'orders.product':    { en:'Product',        pt:'Produto',         es:'Producto',      de:'Produkt',        fr:'Produit' },
  'orders.status.pago':     { en:'Paid',       pt:'Pago',           es:'Pagado',        de:'Bezahlt',        fr:'Payé' },
  'orders.status.pending':  { en:'Pending',    pt:'Aguardando PIX', es:'Pendiente',     de:'Ausstehend',     fr:'En attente' },
  'orders.status.enviado':  { en:'Shipped',    pt:'Enviado',        es:'Enviado',       de:'Versendet',      fr:'Expédié' },
  'orders.status.entregue': { en:'Delivered',  pt:'Entregue',       es:'Entregado',     de:'Geliefert',      fr:'Livré' },
  'orders.status.cancelado':{ en:'Cancelled',  pt:'Cancelado',      es:'Cancelado',     de:'Storniert',      fr:'Annulé' },

  // ── RASTREAR ──────────────────────────────────────
  'track.title':       { en:'Track Order',    pt:'Rastrear Pedido', es:'Rastrear Pedido',de:'Bestellung verfolgen',fr:'Suivre la commande' },
  'track.placeholder': { en:'Tracking code or order number', pt:'Código de rastreio ou número do pedido', es:'Código de seguimiento o número de pedido', de:'Tracking-Code oder Bestellnummer', fr:'Code de suivi ou numéro de commande' },
  'track.btn':         { en:'Search',         pt:'Buscar',          es:'Buscar',        de:'Suchen',         fr:'Rechercher' },
  'track.correios':    { en:'Track on Correios', pt:'Rastrear nos Correios', es:'Rastrear en Correios', de:'Bei Correios verfolgen', fr:'Suivre sur Correios' },

  // ── REDEFINIR SENHA ──────────────────────────────────────
  'reset.title':       { en:'Reset Password', pt:'Redefinir Senha', es:'Restablecer Contraseña', de:'Passwort zurücksetzen', fr:'Réinitialiser le mot de passe' },
  'reset.subtitle':    { en:'Enter your registered email and we\'ll send a reset link.', pt:'Informe seu email cadastrado e enviaremos um link para redefinir sua senha.', es:'Ingresa tu email y te enviaremos un enlace para restablecer tu contraseña.', de:'Geben Sie Ihre E-Mail ein und wir senden Ihnen einen Link.', fr:'Entrez votre email et nous vous enverrons un lien de réinitialisation.' },
  'reset.send':        { en:'Send link',       pt:'Enviar link',     es:'Enviar enlace',  de:'Link senden',   fr:'Envoyer le lien' },
  'reset.back':        { en:'Back to login',   pt:'Voltar ao login', es:'Volver al login',de:'Zurück zum Login',fr:'Retour à la connexion' },
  'reset.new':         { en:'New Password',    pt:'Nova Senha',      es:'Nueva Contraseña',de:'Neues Passwort',fr:'Nouveau mot de passe' },
  'reset.save':        { en:'Save new password',pt:'Salvar nova senha',es:'Guardar nueva contraseña',de:'Neues Passwort speichern',fr:'Enregistrer le nouveau mot de passe' },

  // ── PERFIL ──────────────────────────────────────
  'profile.title':     { en:'My Profile',     pt:'Meu Perfil',      es:'Mi Perfil',     de:'Mein Profil',    fr:'Mon profil' },
  'profile.personal':  { en:'Personal Data',  pt:'Dados Pessoais',  es:'Datos Personales',de:'Persönliche Daten',fr:'Données personnelles' },
  'profile.save':      { en:'Save changes',   pt:'Salvar alterações',es:'Guardar cambios',de:'Änderungen speichern',fr:'Enregistrer les modifications' },
  'profile.password':  { en:'Change Password',pt:'Alterar Senha',   es:'Cambiar Contraseña',de:'Passwort ändern',fr:'Changer le mot de passe' },
  'profile.current':   { en:'Current password',pt:'Senha atual',    es:'Contraseña actual',de:'Aktuelles Passwort',fr:'Mot de passe actuel' },
  'profile.new':       { en:'New password',   pt:'Nova senha',      es:'Nueva contraseña',de:'Neues Passwort', fr:'Nouveau mot de passe' },
  'profile.confirm':   { en:'Confirm',        pt:'Confirmar',       es:'Confirmar',      de:'Bestätigen',     fr:'Confirmer' },
  'profile.change':    { en:'Change password',pt:'Alterar senha',   es:'Cambiar contraseña',de:'Passwort ändern',fr:'Changer le mot de passe' },
  'profile.logout':    { en:'Logout',         pt:'Sair da conta',   es:'Cerrar sesión',  de:'Abmelden',       fr:'Se déconnecter' },

  // ── PÁGINAS INSTITUCIONAIS ──────────────────────────────────────
  'about.title':       { en:'About Us',       pt:'Quem Somos',      es:'Sobre Nosotros', de:'Über uns',       fr:'À propos' },
  'about.mission.title':{ en:'Our Mission',   pt:'Nossa Missão',    es:'Nuestra Misión', de:'Unsere Mission', fr:'Notre mission' },
  'about.values.title':{ en:'Our Values',     pt:'Nossos Valores',  es:'Nuestros Valores',de:'Unsere Werte',  fr:'Nos valeurs' },
  'about.commitment.title':{ en:'Our Commitment',pt:'Compromisso com o Cliente',es:'Nuestro Compromiso',de:'Unser Engagement',fr:'Notre engagement' },

  'faq.title':         { en:'FAQ',            pt:'Dúvidas Frequentes',es:'Preguntas Frecuentes',de:'Häufige Fragen',fr:'Questions fréquentes' },
  'shipping.title':    { en:'Shipping & Deadlines',pt:'Envio e Prazos',es:'Envíos y Plazos',de:'Versand & Fristen',fr:'Expédition et délais' },
  'returns.title':     { en:'Returns & Exchanges',pt:'Trocas e Devoluções',es:'Devoluciones',de:'Rückgaben',fr:'Retours' },
  'terms.title':       { en:'Terms of Use',   pt:'Termos de Uso',   es:'Términos de Uso',de:'Nutzungsbedingungen',fr:'Conditions d\'utilisation' },
  'privacy.title':     { en:'Privacy Policy', pt:'Política de Privacidade',es:'Política de Privacidad',de:'Datenschutz',fr:'Politique de confidentialité' },

  // ── CONFIRMAÇÃO ──────────────────────────────────────
  'confirm.title':     { en:'Order Confirmed!',pt:'Pedido Confirmado!',es:'¡Pedido Confirmado!',de:'Bestellung bestätigt!',fr:'Commande confirmée!' },
  'confirm.subtitle':  { en:'Your order has been received and is being processed. You will receive updates by email.', pt:'Seu pedido foi recebido e está sendo processado. Você receberá atualizações por email.', es:'Tu pedido fue recibido y está siendo procesado.', de:'Ihre Bestellung wurde empfangen und wird bearbeitet.', fr:'Votre commande a été reçue et est en cours de traitement.' },
  'confirm.vieworders':{ en:'View my orders', pt:'Ver meus pedidos', es:'Ver mis pedidos',de:'Meine Bestellungen',fr:'Voir mes commandes' },
  'confirm.continue':  { en:'Continue shopping',pt:'Continuar comprando',es:'Seguir comprando',de:'Weiter einkaufen',fr:'Continuer les achats' },

  // ── 404 ──────────────────────────────────────
  '404.title':         { en:'Page not found', pt:'Página não encontrada',es:'Página no encontrada',de:'Seite nicht gefunden',fr:'Page non trouvée' },
  '404.subtitle':      { en:'The page you\'re looking for doesn\'t exist or has been moved.',pt:'A página que você procura não existe ou foi movida.',es:'La página que buscas no existe o fue movida.',de:'Die gesuchte Seite existiert nicht oder wurde verschoben.',fr:'La page que vous cherchez n\'existe pas ou a été déplacée.' },
  '404.back':          { en:'Back to store',  pt:'Voltar à loja',   es:'Volver a la tienda',de:'Zurück zum Shop',fr:'Retour à la boutique' },
  // ── QUEM SOMOS ──────────────────────────────────────
  'about.mission.text': {
    en: 'PEPMASTERS was born from a passion for science and human performance. We are a company dedicated to offering high-quality bioactive peptides for athletes, sports practitioners and wellness enthusiasts. We believe that access to advanced compounds must come with information, transparency and responsibility. That is why every product we sell goes through rigorous quality control.',
    pt: 'A PEPMASTERS nasceu da paixão pela ciência e pela performance humana. Somos uma empresa dedicada a oferecer peptídeos bioativos de alta qualidade para atletas, praticantes de esportes e entusiastas do bem-estar. Acreditamos que o acesso a compostos avançados deve vir acompanhado de informação, transparência e responsabilidade. Por isso, cada produto que comercializamos passa por rigoroso controle de qualidade.',
    es: 'PEPMASTERS nació de la pasión por la ciencia y el rendimiento humano. Somos una empresa dedicada a ofrecer péptidos bioactivos de alta calidad para atletas, practicantes de deportes y entusiastas del bienestar.',
    de: 'PEPMASTERS entstand aus der Leidenschaft für Wissenschaft und menschliche Leistungsfähigkeit. Wir sind ein Unternehmen, das hochwertige bioaktive Peptide für Athleten und Wellness-Enthusiasten anbietet.',
    fr: 'PEPMASTERS est né de la passion pour la science et la performance humaine. Nous sommes une entreprise dédiée à offrir des peptides bioactifs de haute qualité pour les athlètes et les passionnés de bien-être.'
  },
  'about.values.science': { en:'Science', pt:'Ciência', es:'Ciencia', de:'Wissenschaft', fr:'Science' },
  'about.values.science.text': { en:'Based on evidence and updated scientific research.', pt:'Baseados em evidências e pesquisa científica atualizada.', es:'Basados en evidencia e investigación científica actualizada.', de:'Basierend auf Beweisen und aktueller wissenschaftlicher Forschung.', fr:'Basés sur des preuves et des recherches scientifiques actualisées.' },
  'about.values.quality': { en:'Quality', pt:'Qualidade', es:'Calidad', de:'Qualität', fr:'Qualité' },
  'about.values.quality.text': { en:'Products with guaranteed purity and origin.', pt:'Produtos com pureza e procedência garantidas.', es:'Productos con pureza y procedencia garantizadas.', de:'Produkte mit garantierter Reinheit und Herkunft.', fr:'Produits avec pureté et provenance garanties.' },
  'about.values.transparency': { en:'Transparency', pt:'Transparência', es:'Transparencia', de:'Transparenz', fr:'Transparence' },
  'about.values.transparency.text': { en:'Clear information about each compound we sell.', pt:'Informações claras sobre cada composto que vendemos.', es:'Información clara sobre cada compuesto que vendemos.', de:'Klare Informationen über jede Verbindung, die wir verkaufen.', fr:'Informations claires sur chaque composé que nous vendons.' },
  'about.values.performance': { en:'Performance', pt:'Performance', es:'Rendimiento', de:'Leistung', fr:'Performance' },
  'about.values.performance.text': { en:'Focus on real results for those seeking evolution.', pt:'Foco em resultados reais para quem busca evolução.', es:'Enfoque en resultados reales para quienes buscan evolución.', de:'Fokus auf echte Ergebnisse für diejenigen, die Entwicklung suchen.', fr:'Focus sur des résultats réels pour ceux qui cherchent à évoluer.' },
  'about.commitment.text': { en:'Our team is always available to answer questions, guide on products and ensure that your shopping experience is the best possible. From the first contact to delivery, we take care of every detail.', pt:'Nossa equipe está sempre disponível para tirar dúvidas, orientar sobre os produtos e garantir que sua experiência de compra seja a melhor possível. Desde o primeiro contato até a entrega, cuidamos de cada detalhe.', es:'Nuestro equipo siempre está disponible para responder preguntas y orientar sobre los productos.', de:'Unser Team ist immer verfügbar, um Fragen zu beantworten und über Produkte zu beraten.', fr:'Notre équipe est toujours disponible pour répondre aux questions et orienter sur les produits.' },

  // ── FAQ ──────────────────────────────────────
  'faq.q1': { en:'What are peptides?', pt:'O que são peptídeos?', es:'¿Qué son los péptidos?', de:'Was sind Peptide?', fr:'Qu'est-ce que les peptides?' },
  'faq.a1': { en:'Peptides are short chains of amino acids that act as signaling agents in the body. They can stimulate processes such as muscle recovery, fat burning, tissue regeneration and hormone production more selectively than traditional compounds.', pt:'Peptídeos são cadeias curtas de aminoácidos que atuam como sinalizadores no organismo. Eles podem estimular processos como recuperação muscular, queima de gordura, regeneração tecidual e produção de hormônios de forma mais seletiva do que compostos tradicionais.', es:'Los péptidos son cadenas cortas de aminoácidos que actúan como señalizadores en el organismo. Pueden estimular procesos como la recuperación muscular, quema de grasa y regeneración tisular.', de:'Peptide sind kurze Aminosäureketten, die als Signalgeber im Körper wirken. Sie können Prozesse wie Muskelregeneration, Fettverbrennung und Hormonproduktion stimulieren.', fr:'Les peptides sont de courtes chaînes d'acides aminés qui agissent comme des signaux dans l'organisme, stimulant la récupération musculaire, la combustion des graisses et la régénération des tissus.' },
  'faq.q2': { en:'Are the products safe?', pt:'Os produtos são seguros?', es:'¿Los productos son seguros?', de:'Sind die Produkte sicher?', fr:'Les produits sont-ils sûrs?' },
  'faq.a2': { en:'All our peptides are supplied with purity certificates. We always recommend consulting a healthcare professional before starting any peptide protocol.', pt:'Todos os nossos peptídeos são fornecidos com laudos de pureza. Recomendamos sempre a consulta com um profissional de saúde antes de iniciar qualquer protocolo com peptídeos.', es:'Todos nuestros péptidos se suministran con certificados de pureza. Recomendamos consultar con un profesional de salud antes de comenzar cualquier protocolo.', de:'Alle unsere Peptide werden mit Reinheitszertifikaten geliefert. Wir empfehlen immer, einen Arzt zu konsultieren, bevor Sie ein Peptidprotokoll beginnen.', fr:'Tous nos peptides sont fournis avec des certificats de pureté. Nous recommandons toujours de consulter un professionnel de santé avant de commencer tout protocole.' },
  'faq.q3': { en:'How is payment made?', pt:'Como é feito o pagamento?', es:'¿Cómo se realiza el pago?', de:'Wie wird die Zahlung durchgeführt?', fr:'Comment le paiement est-il effectué?' },
  'faq.a3': { en:'We accept PIX (instant confirmation), credit card and cryptocurrency (USDT/USDC on Polygon). Orders are processed automatically after payment confirmation.', pt:'Aceitamos PIX (confirmação instantânea), cartão de crédito e criptomoedas (USDT/USDC na Polygon). O pedido é processado automaticamente após a confirmação do pagamento.', es:'Aceptamos PIX, tarjeta de crédito y criptomonedas (USDT/USDC en Polygon). El pedido se procesa automáticamente tras la confirmación del pago.', de:'Wir akzeptieren PIX, Kreditkarte und Kryptowährungen (USDT/USDC auf Polygon). Die Bestellung wird nach Zahlungsbestätigung automatisch bearbeitet.', fr:'Nous acceptons PIX, carte de crédit et cryptomonnaies (USDT/USDC sur Polygon). La commande est traitée automatiquement après confirmation du paiement.' },
  'faq.q4': { en:'What is the delivery time?', pt:'Qual o prazo de entrega?', es:'¿Cuál es el plazo de entrega?', de:'Wie lange dauert die Lieferung?', fr:'Quel est le délai de livraison?' },
  'faq.a4': { en:'We ship via post services. The deadline varies from 5 to 15 business days depending on the region. After shipping, you will receive the tracking code by email.', pt:'Enviamos via Correios (PAC ou SEDEX). O prazo varia de 5 a 15 dias úteis dependendo da região. Após o envio, você recebe o código de rastreio por email.', es:'Enviamos por correo postal. El plazo varía de 5 a 15 días hábiles según la región. Después del envío, recibirás el código de seguimiento por email.', de:'Wir versenden per Post. Die Lieferzeit variiert je nach Region zwischen 5 und 15 Werktagen. Nach dem Versand erhalten Sie den Tracking-Code per E-Mail.', fr:'Nous expédions par courrier postal. Le délai varie de 5 à 15 jours ouvrables selon la région. Après l'expédition, vous recevrez le code de suivi par email.' },
  'faq.q5': { en:'How do I track my order?', pt:'Como rastrear meu pedido?', es:'¿Cómo rastrear mi pedido?', de:'Wie verfolge ich meine Bestellung?', fr:'Comment suivre ma commande?' },
  'faq.a5': { en:'Once the order is shipped, you will receive an email with the tracking code. You can also track directly on our website on the "Track Order" page.', pt:'Assim que o pedido for enviado, você receberá um email com o código de rastreio. Também é possível rastrear diretamente em nosso site na página "Rastrear Pedido".', es:'Una vez enviado el pedido, recibirás un email con el código de seguimiento. También puedes rastrear directamente en nuestro sitio.', de:'Sobald die Bestellung versandt wurde, erhalten Sie eine E-Mail mit dem Tracking-Code. Sie können auch direkt auf unserer Website unter "Bestellung verfolgen" verfolgen.', fr:'Une fois la commande expédiée, vous recevrez un email avec le code de suivi. Vous pouvez également suivre directement sur notre site.' },
  'faq.q6': { en:'Can I cancel my order?', pt:'Posso cancelar meu pedido?', es:'¿Puedo cancelar mi pedido?', de:'Kann ich meine Bestellung stornieren?', fr:'Puis-je annuler ma commande?' },
  'faq.a6': { en:'Orders can be cancelled before shipping. After shipping, our exchange and return policy applies. Contact us as soon as possible to expedite the process.', pt:'Pedidos podem ser cancelados antes do envio. Após o envio, segue nossa política de trocas e devoluções. Entre em contato o quanto antes para agilizarmos.', es:'Los pedidos pueden cancelarse antes del envío. Después del envío, se aplica nuestra política de devoluciones. Contáctanos lo antes posible.', de:'Bestellungen können vor dem Versand storniert werden. Nach dem Versand gilt unsere Rückgaberichtlinie. Kontaktieren Sie uns so schnell wie möglich.', fr:'Les commandes peuvent être annulées avant l'expédition. Après l'expédition, notre politique de retour s'applique. Contactez-nous dès que possible.' },
  'faq.q7': { en:'Do the products require a prescription?', pt:'Os produtos precisam de receita?', es:'¿Los productos necesitan receta?', de:'Benötigen die Produkte ein Rezept?', fr:'Les produits nécessitent-ils une ordonnance?' },
  'faq.a7': { en:'Our peptides are sold for research purposes. For human use, we recommend professional supervision. Please check the current legislation in your country.', pt:'Nossos peptídeos são comercializados para fins de pesquisa. Para uso em humanos, recomendamos acompanhamento profissional. Consulte a legislação vigente no seu país.', es:'Nuestros péptidos se comercializan con fines de investigación. Para uso humano, recomendamos supervisión profesional. Consulte la legislación de su país.', de:'Unsere Peptide werden für Forschungszwecke verkauft. Für den menschlichen Gebrauch empfehlen wir professionelle Begleitung. Bitte prüfen Sie die Gesetzgebung in Ihrem Land.', fr:'Nos peptides sont commercialisés à des fins de recherche. Pour un usage humain, nous recommandons un suivi professionnel. Veuillez vérifier la législation en vigueur dans votre pays.' },
  'faq.q8': { en:'Do you issue invoices?', pt:'Vocês emitem nota fiscal?', es:'¿Emiten factura?', de:'Stellen Sie Rechnungen aus?', fr:'Émettez-vous des factures?' },
  'faq.a8': { en:'Yes, we issue invoices for all purchases. The invoice is sent by email along with the order confirmation.', pt:'Sim, emitimos nota fiscal para todas as compras. A NF é enviada por email junto com a confirmação do pedido.', es:'Sí, emitimos factura para todas las compras. La factura se envía por email junto con la confirmación del pedido.', de:'Ja, wir stellen für alle Einkäufe Rechnungen aus. Die Rechnung wird per E-Mail zusammen mit der Bestellbestätigung gesendet.', fr:'Oui, nous émettons des factures pour tous les achats. La facture est envoyée par email avec la confirmation de commande.' },
  'faq.q9': { en:'Can I use a discount coupon?', pt:'Posso usar cupom de desconto?', es:'¿Puedo usar un cupón de descuento?', de:'Kann ich einen Rabattcode verwenden?', fr:'Puis-je utiliser un coupon de réduction?' },
  'faq.a9': { en:'Yes! If you have a valid coupon, just enter the code in the corresponding field during checkout. The discount is applied automatically.', pt:'Sim! Se você possui um cupom válido, basta inserir o código no campo correspondente durante o checkout. O desconto é aplicado automaticamente.', es:'¡Sí! Si tienes un cupón válido, ingresa el código en el campo correspondiente durante el checkout. El descuento se aplica automáticamente.', de:'Ja! Wenn Sie einen gültigen Gutschein haben, geben Sie den Code während des Checkouts ein. Der Rabatt wird automatisch angewendet.', fr:'Oui! Si vous avez un coupon valide, entrez simplement le code dans le champ correspondant lors du paiement. La remise est appliquée automatiquement.' },

  // ── ENVIO E PRAZOS ──────────────────────────────────────
  'shipping.methods.title': { en:'Shipping Methods', pt:'Modalidades de Envio', es:'Modalidades de Envío', de:'Versandmethoden', fr:'Méthodes d'expédition' },
  'shipping.methods.text': { en:'We work with postal services in PAC and SEDEX modalities. Shipping is automatically calculated based on the destination ZIP code during checkout.', pt:'Trabalhamos com os Correios nas modalidades PAC e SEDEX. O frete é calculado automaticamente com base no CEP de destino durante o checkout.', es:'Trabajamos con servicios postales. El envío se calcula automáticamente según el código postal de destino durante el checkout.', de:'Wir arbeiten mit Postdiensten. Der Versand wird beim Checkout automatisch basierend auf der Postleitzahl berechnet.', fr:'Nous travaillons avec les services postaux. L'expédition est calculée automatiquement en fonction du code postal de destination lors du paiement.' },
  'shipping.processing.title': { en:'Order Processing', pt:'Processamento do Pedido', es:'Procesamiento del Pedido', de:'Bestellbearbeitung', fr:'Traitement de la commande' },
  'shipping.processing.text': { en:'After payment confirmation, the order is processed within up to 2 business days. Orders placed after 2pm or on weekends and holidays are processed on the next business day.', pt:'Após a confirmação do pagamento, o pedido é processado em até 2 dias úteis. Pedidos feitos após as 14h ou em fins de semana e feriados são processados no próximo dia útil.', es:'Tras la confirmación del pago, el pedido se procesa en hasta 2 días hábiles. Los pedidos realizados después de las 14h o en fines de semana se procesan el siguiente día hábil.', de:'Nach der Zahlungsbestätigung wird die Bestellung innerhalb von 2 Werktagen bearbeitet. Nach 14 Uhr oder an Wochenenden aufgegebene Bestellungen werden am nächsten Werktag bearbeitet.', fr:'Après confirmation du paiement, la commande est traitée dans les 2 jours ouvrables. Les commandes passées après 14h ou le week-end sont traitées le jour ouvrable suivant.' },
  'shipping.regions.title': { en:'Regions & Notes', pt:'Regiões e Observações', es:'Regiones y Observaciones', de:'Regionen & Hinweise', fr:'Régions et remarques' },
  'shipping.regions.text': { en:'We ship to the entire national territory. For more remote regions, deadlines may be slightly longer than estimated. During high demand periods, there may be delays in processing.', pt:'Enviamos para todo o território nacional. Para regiões mais remotas, os prazos podem ser ligeiramente maiores. Em períodos de alta demanda, pode haver atrasos no processamento.', es:'Enviamos a todo el territorio nacional. Para regiones más remotas, los plazos pueden ser ligeramente mayores. En períodos de alta demanda, puede haber retrasos.', de:'Wir liefern in das gesamte Staatsgebiet. In abgelegeneren Regionen können die Lieferzeiten etwas länger sein. In Hochsaisons kann es zu Verzögerungen kommen.', fr:'Nous expédions sur tout le territoire national. Dans les régions plus éloignées, les délais peuvent être légèrement plus longs. En période de forte demande, des retards de traitement sont possibles.' },

  // ── TROCAS E DEVOLUÇÕES ──────────────────────────────────────
  'returns.policy.title': { en:'Exchange Policy', pt:'Política de Trocas', es:'Política de Cambios', de:'Umtauschrichtlinie', fr:'Politique d'échange' },
  'returns.policy.text': { en:'We accept exchanges in cases of defective products, transport damage or incorrect shipping. The deadline for requesting an exchange is 7 calendar days after receiving the product.', pt:'Aceitamos trocas em casos de produto com defeito, avaria no transporte ou envio incorreto. O prazo para solicitar a troca é de 7 dias corridos após o recebimento do produto.', es:'Aceptamos cambios en casos de productos defectuosos, daños en el transporte o envío incorrecto. El plazo para solicitar el cambio es de 7 días corridos tras la recepción.', de:'Wir akzeptieren Umtausch bei defekten Produkten, Transportschäden oder falscher Lieferung. Die Frist beträgt 7 Kalendertage nach Erhalt der Ware.', fr:'Nous acceptons les échanges en cas de produit défectueux, de dommages de transport ou d'expédition incorrecte. Le délai est de 7 jours calendaires après réception.' },
  'returns.how.title': { en:'How to Request', pt:'Como Solicitar', es:'Cómo Solicitar', de:'Wie beantragen', fr:'Comment demander' },
  'returns.step1': { en:'Contact our support by email informing the order number and the reason for the request.', pt:'Entre em contato com nosso suporte pelo email informando o número do pedido e o motivo da solicitação.', es:'Contacta con nuestro soporte por email indicando el número de pedido y el motivo de la solicitud.', de:'Kontaktieren Sie unseren Support per E-Mail mit der Bestellnummer und dem Grund der Anfrage.', fr:'Contactez notre support par email en indiquant le numéro de commande et la raison de la demande.' },
  'returns.step2': { en:'Our team will evaluate the case and respond within 2 business days with return instructions.', pt:'Nossa equipe avaliará o caso e retornará em até 2 dias úteis com as instruções para devolução.', es:'Nuestro equipo evaluará el caso y responderá en 2 días hábiles con las instrucciones de devolución.', de:'Unser Team wird den Fall prüfen und innerhalb von 2 Werktagen mit Rückgabeanweisungen antworten.', fr:'Notre équipe évaluera le cas et répondra dans les 2 jours ouvrables avec les instructions de retour.' },
  'returns.step3': { en:'After receiving the returned product, we process the exchange or refund within 5 business days.', pt:'Após recebermos o produto devolvido, processamos a troca ou o reembolso em até 5 dias úteis.', es:'Tras recibir el producto devuelto, procesamos el cambio o reembolso en hasta 5 días hábiles.', de:'Nach Erhalt der zurückgesandten Ware bearbeiten wir den Umtausch oder die Rückerstattung innerhalb von 5 Werktagen.', fr:'Après réception du produit retourné, nous traitons l'échange ou le remboursement dans les 5 jours ouvrables.' },
  'returns.refund.title': { en:'Refund', pt:'Reembolso', es:'Reembolso', de:'Rückerstattung', fr:'Remboursement' },
  'returns.refund.text': { en:'Refunds for PIX payments are made via bank transfer. For credit card, the reversal is processed by the card issuer and may take up to 2 billing cycles to appear.', pt:'Reembolsos para pagamentos via PIX são feitos via transferência bancária. Para cartão de crédito, o estorno é processado diretamente pela operadora e pode levar até 2 faturas para aparecer.', es:'Los reembolsos por PIX se realizan por transferencia bancaria. Para tarjeta de crédito, el reembolso lo procesa la operadora y puede tardar hasta 2 ciclos de facturación.', de:'Rückerstattungen für PIX-Zahlungen erfolgen per Banküberweisung. Bei Kreditkarte wird die Stornierung vom Kartenaussteller bearbeitet und kann bis zu 2 Abrechnungszyklen dauern.', fr:'Les remboursements pour les paiements PIX sont effectués par virement bancaire. Pour les cartes de crédit, le remboursement est traité par l'émetteur et peut prendre jusqu'à 2 cycles de facturation.' },

  // ── TERMOS DE USO ──────────────────────────────────────
  'terms.s1.title': { en:'1. Acceptance of Terms', pt:'1. Aceitação dos Termos', es:'1. Aceptación de los Términos', de:'1. Annahme der Bedingungen', fr:'1. Acceptation des conditions' },
  'terms.s1.text': { en:'By accessing and using the PEPMASTERS website, you agree to these Terms of Use. If you do not agree with any part of these terms, please do not use our services.', pt:'Ao acessar e utilizar o site da PEPMASTERS, você concorda com estes Termos de Uso. Caso não concorde com qualquer parte destes termos, solicitamos que não utilize nossos serviços.', es:'Al acceder y utilizar el sitio de PEPMASTERS, aceptas estos Términos de Uso. Si no estás de acuerdo con alguna parte, te solicitamos que no utilices nuestros servicios.', de:'Durch den Zugriff auf die PEPMASTERS-Website stimmen Sie diesen Nutzungsbedingungen zu. Wenn Sie mit einem Teil nicht einverstanden sind, bitten wir Sie, unsere Dienste nicht zu nutzen.', fr:'En accédant au site PEPMASTERS, vous acceptez ces conditions d'utilisation. Si vous n'êtes pas d'accord avec une partie, veuillez ne pas utiliser nos services.' },
  'terms.s2.title': { en:'2. Product Use', pt:'2. Uso dos Produtos', es:'2. Uso de los Productos', de:'2. Produktverwendung', fr:'2. Utilisation des produits' },
  'terms.s2.text': { en:'The peptides sold by PEPMASTERS are intended for research purposes. Use in humans must be accompanied by a qualified health professional. PEPMASTERS is not responsible for improper use of products.', pt:'Os peptídeos comercializados pela PEPMASTERS são destinados a fins de pesquisa. O uso em humanos deve ser acompanhado por um profissional de saúde qualificado. A PEPMASTERS não se responsabiliza pelo uso inadequado dos produtos.', es:'Los péptidos comercializados por PEPMASTERS están destinados a fines de investigación. El uso en humanos debe ser acompañado por un profesional de salud calificado.', de:'Die von PEPMASTERS verkauften Peptide sind für Forschungszwecke bestimmt. Die Verwendung beim Menschen muss von einem qualifizierten Mediziner begleitet werden.', fr:'Les peptides commercialisés par PEPMASTERS sont destinés à des fins de recherche. L'utilisation chez l'homme doit être accompagnée d'un professionnel de santé qualifié.' },
  'terms.s3.title': { en:'3. Registration and Responsibility', pt:'3. Cadastro e Responsabilidade', es:'3. Registro y Responsabilidad', de:'3. Registrierung und Verantwortung', fr:'3. Inscription et responsabilité' },
  'terms.s3.text': { en:'The user is responsible for the information provided in the registration and for the confidentiality of their password. In case of unauthorized use of your account, notify us immediately.', pt:'O usuário é responsável pelas informações fornecidas no cadastro e pela confidencialidade de sua senha. Em caso de uso não autorizado de sua conta, notifique-nos imediatamente.', es:'El usuario es responsable de la información proporcionada en el registro y de la confidencialidad de su contraseña. En caso de uso no autorizado, notifíquenos de inmediato.', de:'Der Benutzer ist für die bei der Registrierung angegebenen Informationen und die Vertraulichkeit seines Passworts verantwortlich.', fr:'L'utilisateur est responsable des informations fournies lors de l'inscription et de la confidentialité de son mot de passe.' },
  'terms.s4.title': { en:'4. Orders and Payments', pt:'4. Pedidos e Pagamentos', es:'4. Pedidos y Pagos', de:'4. Bestellungen und Zahlungen', fr:'4. Commandes et paiements' },
  'terms.s4.text': { en:'All orders are subject to stock availability and payment confirmation. PEPMASTERS reserves the right to cancel orders in case of suspected fraud or pricing error.', pt:'Todos os pedidos estão sujeitos à disponibilidade de estoque e confirmação de pagamento. A PEPMASTERS reserva o direito de cancelar pedidos em caso de suspeita de fraude ou erro de preço.', es:'Todos los pedidos están sujetos a disponibilidad de stock y confirmación de pago. PEPMASTERS se reserva el derecho de cancelar pedidos en caso de sospecha de fraude.', de:'Alle Bestellungen unterliegen der Lagerverfügbarkeit und der Zahlungsbestätigung. PEPMASTERS behält sich das Recht vor, Bestellungen bei Betrugsverdacht zu stornieren.', fr:'Toutes les commandes sont soumises à la disponibilité des stocks et à la confirmation du paiement. PEPMASTERS se réserve le droit d'annuler des commandes en cas de suspicion de fraude.' },
  'terms.s5.title': { en:'5. Intellectual Property', pt:'5. Propriedade Intelectual', es:'5. Propiedad Intelectual', de:'5. Geistiges Eigentum', fr:'5. Propriété intellectuelle' },
  'terms.s5.text': { en:'All website content — texts, images, logos and layouts — is the exclusive property of PEPMASTERS and may not be reproduced without prior authorization.', pt:'Todo o conteúdo do site — textos, imagens, logotipos e layouts — é de propriedade exclusiva da PEPMASTERS e não pode ser reproduzido sem autorização prévia.', es:'Todo el contenido del sitio es propiedad exclusiva de PEPMASTERS y no puede reproducirse sin autorización previa.', de:'Alle Website-Inhalte sind ausschließliches Eigentum von PEPMASTERS und dürfen nicht ohne vorherige Genehmigung reproduziert werden.', fr:'Tout le contenu du site est la propriété exclusive de PEPMASTERS et ne peut être reproduit sans autorisation préalable.' },
  'terms.s6.title': { en:'6. Changes', pt:'6. Alterações', es:'6. Cambios', de:'6. Änderungen', fr:'6. Modifications' },
  'terms.s6.text': { en:'These terms may be updated at any time. Continued use of the site after changes implies acceptance of the new terms. We recommend periodic review of this page.', pt:'Estes termos podem ser atualizados a qualquer momento. O uso continuado do site após alterações implica na aceitação dos novos termos. Recomendamos revisão periódica desta página.', es:'Estos términos pueden actualizarse en cualquier momento. El uso continuado del sitio tras los cambios implica la aceptación de los nuevos términos.', de:'Diese Bedingungen können jederzeit aktualisiert werden. Die weitere Nutzung der Website nach Änderungen impliziert die Annahme der neuen Bedingungen.', fr:'Ces conditions peuvent être mises à jour à tout moment. L'utilisation continue du site après les modifications implique l'acceptation des nouvelles conditions.' },

  // ── POLÍTICA DE PRIVACIDADE ──────────────────────────────────────
  'privacy.s1.title': { en:'1. Data Collected', pt:'1. Dados Coletados', es:'1. Datos Recopilados', de:'1. Erhobene Daten', fr:'1. Données collectées' },
  'privacy.s1.text': { en:'We collect information voluntarily provided during registration (name, email, tax ID, phone and address) and navigation data to improve the website experience.', pt:'Coletamos informações fornecidas voluntariamente no cadastro (nome, email, CPF, telefone e endereço) e dados de navegação para melhorar a experiência no site.', es:'Recopilamos información proporcionada voluntariamente en el registro (nombre, email, documento, teléfono y dirección) y datos de navegación.', de:'Wir erheben freiwillig bei der Registrierung angegebene Informationen (Name, E-Mail, Steuer-ID, Telefon und Adresse) sowie Navigationsdaten.', fr:'Nous collectons les informations fournies volontairement lors de l'inscription (nom, email, numéro fiscal, téléphone et adresse) et les données de navigation.' },
  'privacy.s2.title': { en:'2. Use of Data', pt:'2. Uso dos Dados', es:'2. Uso de los Datos', de:'2. Datenverwendung', fr:'2. Utilisation des données' },
  'privacy.s2.text': { en:'Your data is used exclusively for order processing, delivery communication and customer support. We do not sell or share your data with third parties, except when necessary for payment processing and delivery.', pt:'Seus dados são utilizados exclusivamente para processamento de pedidos, comunicação sobre entregas e suporte ao cliente. Não vendemos nem compartilhamos seus dados com terceiros.', es:'Tus datos se utilizan exclusivamente para el procesamiento de pedidos, comunicación sobre entregas y soporte al cliente. No vendemos ni compartimos tus datos con terceros.', de:'Ihre Daten werden ausschließlich für die Bestellabwicklung, Lieferkommunikation und Kundensupport verwendet. Wir verkaufen oder teilen Ihre Daten nicht mit Dritten.', fr:'Vos données sont utilisées exclusivement pour le traitement des commandes, la communication sur les livraisons et le support client. Nous ne vendons ni ne partageons vos données.' },
  'privacy.s3.title': { en:'3. Storage and Security', pt:'3. Armazenamento e Segurança', es:'3. Almacenamiento y Seguridad', de:'3. Speicherung und Sicherheit', fr:'3. Stockage et sécurité' },
  'privacy.s3.text': { en:'All information is stored on secure servers. We use encryption and security best practices to protect your data against unauthorized access.', pt:'Todas as informações são armazenadas em servidores seguros. Utilizamos criptografia e boas práticas de segurança para proteger seus dados contra acesso não autorizado.', es:'Toda la información se almacena en servidores seguros. Utilizamos encriptación y buenas prácticas de seguridad para proteger tus datos.', de:'Alle Informationen werden auf sicheren Servern gespeichert. Wir verwenden Verschlüsselung und Sicherheitsbestpraktiken zum Schutz Ihrer Daten.', fr:'Toutes les informations sont stockées sur des serveurs sécurisés. Nous utilisons le chiffrement et les bonnes pratiques de sécurité pour protéger vos données.' },
  'privacy.s4.title': { en:'4. Cookies', pt:'4. Cookies', es:'4. Cookies', de:'4. Cookies', fr:'4. Cookies' },
  'privacy.s4.text': { en:'We use cookies to keep your session active and improve navigation. You can disable cookies in your browser settings, however some features may be affected.', pt:'Utilizamos cookies para manter sua sessão ativa e melhorar a navegação. Você pode desativar cookies nas configurações do seu navegador, porém algumas funcionalidades podem ser afetadas.', es:'Utilizamos cookies para mantener tu sesión activa y mejorar la navegación. Puedes desactivar las cookies en la configuración de tu navegador.', de:'Wir verwenden Cookies, um Ihre Sitzung aktiv zu halten und die Navigation zu verbessern. Sie können Cookies in Ihren Browsereinstellungen deaktivieren.', fr:'Nous utilisons des cookies pour maintenir votre session active et améliorer la navigation. Vous pouvez désactiver les cookies dans les paramètres de votre navigateur.' },
  'privacy.s5.title': { en:'5. Your Rights (GDPR/LGPD)', pt:'5. Seus Direitos (LGPD)', es:'5. Tus Derechos (RGPD)', de:'5. Ihre Rechte (DSGVO)', fr:'5. Vos droits (RGPD)' },
  'privacy.s5.text': { en:'In accordance with applicable data protection law, you have the right to access, correct, delete or request the portability of your data. To exercise these rights, contact our support.', pt:'Em conformidade com a Lei Geral de Proteção de Dados (Lei 13.709/2018), você tem direito a acessar, corrigir, excluir ou solicitar a portabilidade de seus dados.', es:'De conformidad con la ley de protección de datos aplicable, tienes derecho a acceder, corregir, eliminar o solicitar la portabilidad de tus datos.', de:'Gemäß der geltenden Datenschutzgesetzgebung haben Sie das Recht, auf Ihre Daten zuzugreifen, diese zu korrigieren, zu löschen oder deren Übertragbarkeit zu verlangen.', fr:'Conformément à la loi applicable sur la protection des données, vous avez le droit d'accéder, de corriger, de supprimer ou de demander la portabilité de vos données.' },
  'privacy.s6.title': { en:'6. Contact', pt:'6. Contato', es:'6. Contacto', de:'6. Kontakt', fr:'6. Contact' },
  'privacy.s6.text': { en:'For questions about this policy or to exercise your rights, please contact us via the email available on the website contact page.', pt:'Para dúvidas sobre esta política ou exercício de direitos, entre em contato pelo email disponível na página de contato do site.', es:'Para dudas sobre esta política o ejercicio de derechos, contáctanos por el email disponible en la página de contacto del sitio.', de:'Für Fragen zu dieser Richtlinie oder zur Ausübung Ihrer Rechte kontaktieren Sie uns bitte über die auf der Website angegebene E-Mail-Adresse.', fr:'Pour toute question sur cette politique ou pour exercer vos droits, contactez-nous via l'email disponible sur la page de contact du site.' },

};
